apiVersion: apiextensions.crossplane.io/v1alpha1
kind: EnvironmentConfig
metadata:
  name: hsp-addons
  labels:
    config: hsp-addons
data:
  resourcePrefix: "test"
  clusterFqdn: "example.com"
  accountId: "123456789012"
  region: "us-east-1"
  partition: "aws"
  tags:
    Environment: "test"
  eks:
    clusterName: "test-cluster"
    oidcIssuer: "https://oidc.eks.us-east-1.amazonaws.com/id/EXAMPLE"
